"""Initial migration: Create tareas table

Revision ID: 64724d39bf0c
Revises: 
Create Date: 2025-11-22 19:08:33.494047

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64724d39bf0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('tareas_titulo_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_tareas_titulo'), ['titulo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tareas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tareas_titulo'))
        batch_op.create_unique_constraint(batch_op.f('tareas_titulo_key'), ['titulo'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
